spring:
  thymeleaf:
    enabled: true  #开启thymeleaf视图解析
    encoding: utf-8  #编码
    prefix: classpath:/templates/  #前缀
    cache: false  #是否使用缓存
    mode: HTML  #严格的HTML语法模式
    suffix: .html  #后缀名

  datasource:
    #1.JDBC
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seckill?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT
    username: root
    password: 1234
#    druid:
#      #2.连接池配置
#      #初始化连接池的连接数量 大小，最小，最大
#      initial-size: 5
#      min-idle: 5
#      max-active: 20
#      #配置获取连接等待超时的时间
#      max-wait: 60000
#      #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
#      time-between-eviction-runs-millis: 60000
#      # 配置一个连接在池中最小生存的时间，单位是毫秒
#      min-evictable-idle-time-millis: 30000
#      validation-query: SELECT 1 FROM DUAL
#      test-while-idle: true
#      test-on-borrow: true
#      test-on-return: false
#      # 是否缓存preparedStatement，也就是PSCache  官方建议MySQL下建议关闭   个人建议如果想用SQL防火墙 建议打开
#      pool-prepared-statements: true
#      max-pool-prepared-statement-per-connection-size: 20
#      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
#      filter:
#        stat:
#          merge-sql: true
#          slow-sql-millis: 5000
#      #3.基础监控配置
#      web-stat-filter:
#        enabled: true
#        url-pattern: /*
#        #设置不统计哪些URL
#        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
#        session-stat-enable: true
#        session-stat-max-count: 100
  redis:
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        max-idle: 500
        max-active: 1000
        max-wait: 3
    timeout: 10000ms